Repository decide-ganimedes/decide-ganimedes, pull requests merged in 2019-01, with the labels that each got.

#59 <fix> Recuento de votos
  decide/voting/models.py
  decide/voting/tests.py
Labels: bug

#60 <feat><fix> Actualización de postprocesados
  decide/postproc/tests.py
  decide/postproc/views.py
  decide/voting/models.py
  decide/voting/tests.py
Labels: bug, mejora

#74 <feat> Traducción, exportación y gráficas mejoradas
  decide/base/templates/base.html
  decide/locale/ca/LC_MESSAGES/django.po
  decide/locale/es/LC_MESSAGES/django.po
  decide/visualizer/render.py
  decide/visualizer/templates/visualizer/ended.html
  decide/visualizer/templates/visualizer/ended_export.html
  decide/visualizer/templates/visualizer/list_ended.html
  decide/visualizer/templates/visualizer/ongoing.html
  decide/visualizer/views.py
Labels: mejora

#79 <style> Página principal adaptada
  decide/base/static/decide/css/base.css
  decide/base/templates/base.html
  decide/locale/ca/LC_MESSAGES/django.po
  decide/locale/es/LC_MESSAGES/django.po
  decide/visualizer/render.py
  decide/visualizer/templates/visualizer/ended.html
  decide/visualizer/templates/visualizer/ended_export.html
  decide/visualizer/templates/visualizer/ongoing.html
Labels: mejora

#80 Tests post-procesado
  decide/postproc/tests.py
  decide/postproc/views.py
Labels: mejora
